import type { StyleDef, StyleKey, L1Item, L2Item, L3Item, L4Item, Rank, XpValues } from '@/types/game'

// Pharma sales context: the player is a medical sales rep calling on doctors and
// pharmacies. Scenarios are pools — the scenario engine draws a fresh random
// subset each session (see scenario-engine.ts). Arabic mirror lives in
// game-data-ar.ts, keyed by the SAME ids.

export const STYLES: Record<StyleKey, StyleDef> = {
  driver:     { name:'Driver',     cls:'driver',     icon:'▲', drive:'Control & Achievement', blurb:'Assertive, direct, ROI-focused. Decides fast and dislikes wasted time.' },
  expressive: { name:'Expressive', cls:'expressive', icon:'✦', drive:'Recognition & Ideas',   blurb:'Enthusiastic, visionary, collaborative. Loves big ideas and being seen as innovative.' },
  amiable:    { name:'Amiable',    cls:'amiable',    icon:'♥', drive:'Security & Harmony',    blurb:'Warm, patient, relationship-first. Risk-averse and seeks consensus.' },
  analytical: { name:'Analytical', cls:'analytical', icon:'◆', drive:'Certainty & Accuracy',  blurb:'Precise, logical, data-driven. Wants evidence and time to evaluate.' },
}

export const STYLE_ORDER: StyleKey[] = ['driver','expressive','amiable','analytical']

// ───────────────────────── LEVEL 1 · Style Scan (pool of 45) ─────────────────────────
export const L1: L1Item[] = [
  { id:101, style:'driver', name:'Dr. Khalid · Surgeon', persona:'Surgeon',
    cues:['Stops you early: "Which patients, what outcome — give me the bottom line."','Glances at the OR schedule twice.','Wants two options and will decide on the spot.'] },
  { id:102, style:'analytical', name:'Dr. Salim · Cardiologist', persona:'Cardiologist',
    cues:['"Where\'s the head-to-head trial data, not the brochure?"','Re-reads the methodology before commenting.','Won\'t commit until he has reviewed the study design.'] },
  { id:103, style:'expressive', name:'Dr. Hana · Dermatologist', persona:'Dermatologist',
    cues:['Excited to be among the first to use a novel option.','Talks about presenting her cases at a conference.','Wants the brand to make her clinic look cutting-edge.'] },
  { id:104, style:'amiable', name:'Dr. Mona · Family GP', persona:'Family GP',
    cues:['Asks how her regular patients will tolerate a switch.','Wants to start slowly with a few patients.','Values a rep she can trust over the long term.'] },
  { id:105, style:'analytical', name:'Fadi · Hospital Pharmacist', persona:'Hospital Pharmacist',
    cues:['Asks for stability and storage data.','Checks each formulary inclusion criterion.','Wants the full dossier before listing anything.'] },
  { id:106, style:'driver', name:'Ziad · Pharmacy Owner', persona:'Pharmacy Owner',
    cues:['"What\'s my margin and how fast does it move?"','Counts shelf turnover as you talk.','Decides immediately if the numbers work.'] },
  { id:107, style:'expressive', name:'Dr. Yousef · Psychiatrist (KOL)', persona:'Psychiatrist · KOL',
    cues:['Riffs on a bold new treatment approach.','Wants to be recognized as a thought leader.','Asks about advisory boards and speaking slots.'] },
  { id:108, style:'amiable', name:'Huda · Community Pharmacist', persona:'Community Pharmacist',
    cues:['Asks how it helps her regular customers.','Wants reassurance on side effects so she can advise patients.','Prefers a steady relationship over a one-off deal.'] },
  { id:109, style:'analytical', name:'Dr. Omar · Endocrinologist', persona:'Endocrinologist',
    cues:['Quotes the latest treatment guideline.','Asks for the exact HbA1c reduction figures.','Methodical — wants time to evaluate.'] },
  { id:110, style:'driver', name:'Dr. Tarek · Orthopedic Surgeon', persona:'Orthopedic Surgeon',
    cues:['Interrupts: "Bottom line on recovery time?"','Impatient with mechanism-of-action detail.','Frames everything around patient throughput.'] },
  { id:111, style:'driver', name:'Sara · Chain Pharmacy Buyer', persona:'Chain Buyer',
    cues:['"Give me your best price and terms."','Watching her turnover targets.','Wants two SKU options and a fast decision.'] },
  { id:112, style:'amiable', name:'Dr. Layla · Pediatrician', persona:'Pediatrician',
    cues:['Worried about safety in children.','Wants to consult colleagues first.','Gentle and relationship-first.'] },
  { id:113, style:'analytical', name:'Dr. Nadia · Oncologist', persona:'Oncologist',
    cues:['Requests survival-curve and subgroup data.','Questions the sample size of your evidence.','Cautious — avoids quick conclusions.'] },
  { id:114, style:'expressive', name:'Rami · Pharmacy Manager', persona:'Pharmacy Manager',
    cues:['Wants an eye-catching counter display.','Loves being the "first pharmacy" with a launch.','Talks fast about promotions and visibility.'] },
  { id:115, style:'driver', name:'Dr. Sami · High-Prescriber GP', persona:'GP',
    cues:['"How many samples can you leave? I\'m slammed."','Wants speed and simplicity.','Decides fast and moves on.'] },
  { id:116, style:'analytical', name:'Dr. Reem · Rheumatologist', persona:'Rheumatologist',
    cues:['Asks for the long-term safety registry.','Reviews the prescribing information line by line.','Will not be rushed into a decision.'] },
  { id:117, style:'amiable', name:'Karim · Community Pharmacist', persona:'Community Pharmacist',
    cues:['Asks how the change affects his elderly customers.','Checks with his partner before ordering.','Values trust above a quick sale.'] },
  { id:118, style:'expressive', name:'Dr. Faris · ENT Specialist', persona:'ENT Specialist',
    cues:['Enthusiastic about an innovative formulation.','Wants co-marketing and visibility.','Jumps quickly between three ideas.'] },
  { id:119, style:'driver', name:'Dr. Bassam · ER Physician', persona:'ER Physician',
    cues:['"Quick — I\'m between codes. The one-line indication?"','Watches the trauma board mid-sentence.','Wants the fastest-acting option and decides now.'] },
  { id:120, style:'driver', name:'Dr. Hadi · Clinic Owner (GP)', persona:'Clinic Owner',
    cues:['"What\'s the turnaround for my patients?"','Runs a packed, high-volume clinic.','Picks whatever moves patients through fastest.'] },
  { id:121, style:'driver', name:'Lina · Hospital Procurement', persona:'Procurement Officer',
    cues:['"Best price, fastest delivery — decide today."','Tracks the budget line as you speak.','Wants two quotes and a quick call.'] },
  { id:122, style:'analytical', name:'Dr. Samira · Nephrologist', persona:'Nephrologist',
    cues:['Asks for renal-dosing and creatinine-clearance data.','Reads the SmPC before responding.','Will not be rushed into prescribing.'] },
  { id:123, style:'analytical', name:'Dr. Tamer · Infectious Disease', persona:'Infectious Disease',
    cues:['Wants resistance rates and MIC values.','Cross-checks against the latest guideline.','Cautious — avoids empirical leaps.'] },
  { id:124, style:'analytical', name:'Mariam · Quality Pharmacist', persona:'Quality Pharmacist',
    cues:['Asks for batch records and the certificate of analysis.','Verifies every claim against documentation.','Methodical and detail-driven.'] },
  { id:125, style:'expressive', name:'Dr. Lina · Aesthetic Dermatologist', persona:'Aesthetic Dermatologist',
    cues:['Loves novel, showcase-worthy results.','Wants striking before-and-after cases to share.','Talks fast and jumps between ideas.'] },
  { id:126, style:'expressive', name:'Dr. Nabil · Cardiologist (KOL)', persona:'Cardiologist · KOL',
    cues:['Wants to lead a regional symposium.','Excited to be first with a new approach.','Energetic and full of big-picture ideas.'] },
  { id:127, style:'expressive', name:'Tariq · Pharmacy Owner', persona:'Pharmacy Owner',
    cues:['Wants the newest product to stand out.','Loves bold promotional displays.','Talks fast about being the go-to pharmacy.'] },
  { id:128, style:'amiable', name:'Dr. Suha · Geriatrician', persona:'Geriatrician',
    cues:['Worried about polypharmacy in elderly patients.','Wants to consult caregivers first.','Gentle and relationship-first.'] },
  { id:129, style:'amiable', name:'Dr. Maha · Pediatric GP', persona:'Pediatric GP',
    cues:['Cautious about safety in children.','Wants reassurance before changing anything.','Values a long, trusting relationship.'] },
  { id:130, style:'amiable', name:'Noor · Community Pharmacist', persona:'Community Pharmacist',
    cues:['Cares deeply about her regular customers.','Asks how to counsel patients properly.','Avoids pushy, one-off deals.'] },
  { id:131, style:'driver', name:'Dr. Wael · Vascular Surgeon', persona:'Vascular Surgeon',
    cues:['"Bottom line — does it cut my complication rate? Yes or no."','Taps the table waiting for the number.','Wants two options and decides between cases.'] },
  { id:132, style:'analytical', name:'Dr. Huda · Pulmonologist', persona:'Pulmonologist',
    cues:['Asks for the spirometry endpoints and the trial population.','Reads the inclusion criteria before commenting.','Won\'t commit until she has reviewed the evidence.'] },
  { id:133, style:'expressive', name:'Dr. Kareem · Plastic Surgeon', persona:'Plastic Surgeon',
    cues:['Wants showcase results he can present at a congress.','Excited to be first with a novel technique.','Talks fast and jumps between ideas.'] },
  { id:134, style:'amiable', name:'Dr. Rana · OB-GYN', persona:'OB-GYN',
    cues:['Worried about safety in pregnancy.','Wants to start with a few patients she knows well.','Values a rep she can trust over time.'] },
  { id:135, style:'driver', name:'Dr. Majed · Gastroenterologist', persona:'Gastroenterologist',
    cues:['"I have a full endoscopy list — give me the headline."','Impatient with mechanism detail.','Frames everything around patient throughput.'] },
  { id:136, style:'analytical', name:'Dr. Sana · Neurologist', persona:'Neurologist',
    cues:['Asks for the relapse-rate data and the comparator arm.','Questions the study\'s methodology.','Methodical — wants time to evaluate.'] },
  { id:137, style:'expressive', name:'Dr. Adel · Sports Medicine', persona:'Sports Medicine',
    cues:['Loves an innovative, talked-about approach.','Wants co-marketing and clinic visibility.','Energetic and full of big ideas.'] },
  { id:138, style:'amiable', name:'Dr. Lama · Palliative Care', persona:'Palliative Care',
    cues:['Focused on patient comfort above all.','Wants reassurance on tolerability.','Gentle and relationship-first.'] },
  { id:139, style:'driver', name:'Basel · Distributor Buyer', persona:'Distributor Buyer',
    cues:['"Best price and supply terms — decide today."','Tracks his volume targets as you talk.','Wants two options and a fast call.'] },
  { id:140, style:'analytical', name:'Dr. Faisal · Ophthalmologist', persona:'Ophthalmologist',
    cues:['Asks for the exact intraocular-pressure reduction figures.','Reviews the prescribing information line by line.','Cautious — avoids quick conclusions.'] },
  { id:141, style:'expressive', name:'Dr. Dina · Endocrinologist (KOL)', persona:'Endocrinologist · KOL',
    cues:['Wants to champion a new patient-care program.','Excited to be recognized as a thought leader.','Talks fast about big-picture ideas.'] },
  { id:142, style:'amiable', name:'Dr. Ola · Family GP', persona:'Family GP',
    cues:['Asks how loyal patients will handle a change.','Prefers to ease in slowly.','Warm and relationship-first.'] },
  { id:143, style:'analytical', name:'Dr. Hisham · Urologist', persona:'Urologist',
    cues:['Wants head-to-head comparative data.','Re-reads the methodology before committing.','Will not be rushed into a decision.'] },
  { id:144, style:'expressive', name:'Walid · Pharmacy Chain Marketer', persona:'Chain Marketer',
    cues:['Wants an eye-catching launch campaign.','Loves being the first chain with a new product.','Talks fast about visibility and promotions.'] },
  { id:145, style:'amiable', name:'Hala · Community Pharmacist', persona:'Community Pharmacist',
    cues:['Cares about her regular customers\' wellbeing.','Wants reassurance before recommending a switch.','Avoids pushy, one-off deals.'] },
  // ── Iraq pack ──
  { id:1101, style:'driver', name:'Dr. Haider · Cardiologist', persona:'Cardiologist · Medical City',
    cues:['"Bottom line — does it cut readmissions? Yes or no, my clinic is full."','Glances twice at the packed waiting hall.','Wants two options and decides on the spot.'] },
  { id:1102, style:'analytical', name:'Dr. Zainab · Endocrinologist', persona:'Endocrinologist · Basra',
    cues:['Asks for the exact HbA1c figures and the trial population.','Re-reads the leaflet before commenting.','Won\'t commit until she has reviewed the data.'] },
  { id:1103, style:'expressive', name:'Dr. Mustafa · Dermatologist', persona:'Dermatologist · Mansour',
    cues:['Excited to be the first in Baghdad with a novel option.','Talks about presenting his cases at the Iraqi dermatology conference.','Wants the brand to make his clinic look cutting-edge.'] },
  { id:1104, style:'amiable', name:'Dr. Noor · Family GP', persona:'Family GP · Karrada',
    cues:['Asks how her loyal patients will handle a switch.','Wants to start slowly with a few patients.','Values a rep she can trust over the long term.'] },
  { id:1105, style:'amiable', name:'Abu Ahmed · Community Pharmacist', persona:'Community Pharmacist',
    cues:['Asks how it helps his regular neighborhood customers.','Wants reassurance on counseling patients about side effects.','Prefers a steady relationship over a one-off deal.'] },
  { id:1106, style:'analytical', name:'Hassan · Hospital Pharmacist', persona:'Hospital Pharmacist · Medical City',
    cues:['Asks for stability and storage data given the summer heat.','Checks each Kimadia formulary criterion.','Wants the full dossier before listing anything.'] },
  { id:1107, style:'driver', name:'Hajji Salam · Pharmacy Owner', persona:'Pharmacy Owner',
    cues:['"What\'s my margin and how fast does it move?"','Counts shelf turnover as you talk.','Decides immediately if the numbers work.'] },
  { id:1108, style:'expressive', name:'Dr. Sajjad · Orthopedic Surgeon (KOL)', persona:'Orthopedic Surgeon · KOL',
    cues:['Riffs on a bold new surgical technique.','Wants to be recognized as a thought leader at conferences.','Asks about speaking slots and advisory roles.'] },
]

// ───────────────────────── LEVEL 2 · Crisis Mode (pool of 27) ─────────────────────────
export const L2: L2Item[] = [
  { id:201, style:'analytical', name:'Dr. Salim · Cardiologist', crisis:'"A competitor rep just showed me data saying your drug is no better. Convince me or leave."',
    q:'Dr. Salim (Analytical) is challenging you. Choose your path.',
    opts:[
      { t:'Walk through the head-to-head endpoints and number-needed-to-treat, calmly.', r:'win', why:'Winning Strategy. Evidence and a logical breakdown satisfy the Analytical drive for Certainty & Accuracy.' },
      { t:'Insist your drug is simply better and ask him to trust your experience.',       r:'escalate', why:'Dismissing data raises an Analytical\'s stress and erodes trust.' },
      { t:'Appeal emotionally to your long relationship.',                                  r:'escalate', why:'Emotion over evidence ignores what an Analytical needs under pressure.' },
    ]},
  { id:202, style:'driver', name:'Dr. Khalid · Surgeon', crisis:'"I have 20 patients waiting. Why are you wasting my time?"',
    q:'Dr. Khalid (Driver) is stressed. Choose your path.',
    opts:[
      { t:'Give one-line benefit, then two options, and let him decide.', r:'win', why:'Winning Strategy. Brevity, options and control feed the Driver drive for Control & Achievement.' },
      { t:'Launch into the full mechanism-of-action story.',              r:'escalate', why:'Long detail with no decision point escalates a stressed Driver.' },
      { t:'Ask how he\'s coping with the busy clinic first.',             r:'escalate', why:'A Driver reads this as a delay, not empathy.' },
    ]},
  { id:203, style:'amiable', name:'Huda · Community Pharmacist', crisis:'"A customer complained of side effects from your product — I\'m nervous about recommending it."',
    q:'Huda (Amiable) is worried. Choose your path.',
    opts:[
      { t:'Acknowledge the concern, share the safety profile and a patient-counseling guide, and offer support.', r:'win', why:'Winning Strategy. Reassurance and a safety net satisfy the Amiable drive for Security & Harmony.' },
      { t:'Push her to keep ordering — one complaint is nothing.',         r:'escalate', why:'Pressure attacks the Amiable need for security; stress spikes.' },
      { t:'Tell her the data says it\'s fine and move on.',               r:'escalate', why:'Data alone doesn\'t reassure an Amiable — she needs to feel supported.' },
    ]},
  { id:204, style:'expressive', name:'Dr. Hana · Dermatologist', crisis:'"The conference panel dismissed the approach I championed. I look foolish."',
    q:'Dr. Hana (Expressive) is deflated. Choose your path.',
    opts:[
      { t:'Recognize her leadership, then co-build the next case series together.', r:'win', why:'Winning Strategy. Recognition plus fresh ideas restore the Expressive drive for Recognition & Ideas.' },
      { t:'Send her a chart explaining why the approach underperformed.',  r:'escalate', why:'Cold analysis deflates an Expressive and raises stress.' },
      { t:'Tell her to toughen up and not take it personally.',            r:'escalate', why:'Denying recognition escalates an Expressive fast.' },
    ]},
  { id:205, style:'analytical', name:'Fadi · Hospital Pharmacist', crisis:'"Your stability data doesn\'t match our storage conditions. This can\'t be listed."',
    q:'Fadi (Analytical) has blocked the listing. Choose your path.',
    opts:[
      { t:'Go through the stability dossier and your storage range point by point.', r:'win', why:'Winning Strategy. Precision on the exact data resolves the Analytical objection.' },
      { t:'Reassure him vaguely that it will be fine.',                    r:'escalate', why:'Vague comfort ignores his drive for certainty.' },
      { t:'Point out that other hospitals listed it, so he should too.',   r:'escalate', why:'Social proof doesn\'t answer an Analytical\'s data question.' },
    ]},
  { id:206, style:'driver', name:'Ziad · Pharmacy Owner', crisis:'"Your product is sitting on my shelf, not moving. I want to return it."',
    q:'Ziad (Driver) wants out. Choose your path.',
    opts:[
      { t:'Offer two concrete sell-through actions with the margin impact, his pick.', r:'win', why:'Winning Strategy. Action, options and control feed the Driver drive.' },
      { t:'Tell the long brand-heritage story to rebuild interest.',       r:'escalate', why:'Narrative with no decision point frustrates a stressed Driver.' },
      { t:'Remind him of your loyal relationship and ask him to be patient.', r:'escalate', why:'A Driver reads patience as no progress on the number.' },
    ]},
  { id:207, style:'amiable', name:'Dr. Mona · Family GP', crisis:'"You\'re pushing me to switch all my patients too fast — I\'m not comfortable."',
    q:'Dr. Mona (Amiable) feels pressured. Choose your path.',
    opts:[
      { t:'Reassure her; propose switching only new patients first, with your support.', r:'win', why:'Winning Strategy. A low-risk phased path satisfies the Amiable drive for Security.' },
      { t:'Push for a full switch now to hit the cycle target.',           r:'escalate', why:'Pressure attacks the Amiable need for security; stress rises.' },
      { t:'Tell her the data proves it\'s safe, so she should just do it.', r:'escalate', why:'Data alone doesn\'t reassure an Amiable under pressure.' },
    ]},
  { id:208, style:'expressive', name:'Dr. Yousef · Psychiatrist (KOL)', crisis:'"Another company offered me a bigger speaking role. Why should I stay with you?"',
    q:'Dr. Yousef (Expressive) is courting offers. Choose your path.',
    opts:[
      { t:'Recognize his influence and offer a visible platform for his ideas — a symposium and advisory role.', r:'win', why:'Winning Strategy. Recognition and a stage feed the Expressive drive.' },
      { t:'Counter with cold, detailed contract terms.',                   r:'escalate', why:'Spreadsheet-first deflates an Expressive who wants to be seen.' },
      { t:'Downplay the competitor and ask him to stay out of loyalty.',   r:'escalate', why:'Denying his standing escalates an Expressive.' },
    ]},
  { id:209, style:'driver', name:'Sara · Chain Pharmacy Buyer', crisis:'"Your price is higher than the generic. Give me a reason in ten seconds."',
    q:'Sara (Driver) wants it fast. Choose your path.',
    opts:[
      { t:'Lead with margin and turnover, give two pack options, her call.', r:'win', why:'Winning Strategy. Numbers, options and a fast decision feed the Driver drive.' },
      { t:'Deliver a clinical lecture on why the brand is superior.',        r:'escalate', why:'A buyer under time pressure reads this as wasted time.' },
      { t:'Ask how she feels about stocking quality products.',             r:'escalate', why:'A Driver wants the number, not a feelings question.' },
    ]},
  { id:210, style:'analytical', name:'Dr. Omar · Endocrinologist', crisis:'"Your HbA1c claim isn\'t in the latest guideline. I can\'t prescribe on marketing."',
    q:'Dr. Omar (Analytical) wants proof. Choose your path.',
    opts:[
      { t:'Show the pivotal trial and exactly where its evidence sits relative to the guideline.', r:'win', why:'Winning Strategy. Locating the evidence precisely satisfies the Analytical drive.' },
      { t:'Make an emotional case about patients who could benefit.',       r:'escalate', why:'Emotion doesn\'t answer an evidence objection.' },
      { t:'Tell him most of his peers already prescribe it.',               r:'escalate', why:'Popularity isn\'t proof for an Analytical.' },
    ]},
  { id:211, style:'driver', name:'Dr. Bassam · ER Physician', crisis:'"I used it once and the patient bounced back to the ER. Why trust it again?"',
    q:'Dr. Bassam (Driver) is skeptical and rushed. Choose your path.',
    opts:[
      { t:'Give the one-line outcome data, then two protocol options, and let him decide.', r:'win', why:'Winning Strategy. Brevity, evidence and control feed the Driver drive.' },
      { t:'Explain the full pharmacology of why the bounce-back happened.', r:'escalate', why:'Long detail with no decision frustrates a rushed Driver.' },
      { t:'Ask how the case made him feel about the drug.',                r:'escalate', why:'A Driver reads a feelings question as wasted time.' },
    ]},
  { id:212, style:'analytical', name:'Dr. Samira · Nephrologist', crisis:'"Your dosing table doesn\'t cover renal impairment. I can\'t use it safely."',
    q:'Dr. Samira (Analytical) needs proof. Choose your path.',
    opts:[
      { t:'Walk through the renal-dosing data and the clearance study, stage by stage.', r:'win', why:'Winning Strategy. Precise data resolves the Analytical objection.' },
      { t:'Reassure her the dose is "probably fine" in most patients.',    r:'escalate', why:'Vague reassurance ignores her drive for certainty.' },
      { t:'Tell her other nephrologists prescribe it without issue.',      r:'escalate', why:'Anecdote isn\'t evidence for an Analytical.' },
    ]},
  { id:213, style:'expressive', name:'Dr. Lina · Aesthetic Dermatologist', crisis:'"A patient posted a bad result and tagged my clinic. I\'m embarrassed."',
    q:'Dr. Lina (Expressive) feels exposed. Choose your path.',
    opts:[
      { t:'Recognize her reputation and co-create a corrective showcase case together.', r:'win', why:'Winning Strategy. Recognition plus a fresh idea restore the Expressive drive.' },
      { t:'Send her a technical errata sheet explaining the bad result.',   r:'escalate', why:'Cold analysis deflates an Expressive.' },
      { t:'Tell her one online post doesn\'t matter — ignore it.',         r:'escalate', why:'Dismissing her standing escalates an Expressive.' },
    ]},
  { id:214, style:'amiable', name:'Dr. Suha · Geriatrician', crisis:'"Adding another drug for my frail elderly patients really worries me."',
    q:'Dr. Suha (Amiable) is anxious. Choose your path.',
    opts:[
      { t:'Acknowledge it; offer a low-dose start with monitoring and your support.', r:'win', why:'Winning Strategy. A safe, supported path satisfies the Amiable drive for security.' },
      { t:'Push her to hit the adoption target this cycle.',               r:'escalate', why:'Pressure attacks the Amiable need for security.' },
      { t:'Tell her the safety data means there\'s nothing to worry about.', r:'escalate', why:'Data alone doesn\'t reassure an anxious Amiable.' },
    ]},
  { id:215, style:'driver', name:'Lina · Hospital Procurement', crisis:'"Your delivery was late last quarter. Give me one reason to reorder."',
    q:'Lina (Driver) is unimpressed. Choose your path.',
    opts:[
      { t:'Offer two supply-guarantee options with the cost impact, her call.', r:'win', why:'Winning Strategy. Action, options and control feed the Driver drive.' },
      { t:'Apologize at length for the past delay.',                       r:'escalate', why:'Dwelling on the past reads as no progress to a Driver.' },
      { t:'Appeal to your long supplier relationship.',                    r:'escalate', why:'A Driver wants the fix, not sentiment.' },
    ]},
  { id:216, style:'analytical', name:'Mariam · Quality Pharmacist', crisis:'"Your certificate of analysis is missing the impurity profile. I can\'t approve the batch."',
    q:'Mariam (Analytical) blocked the batch. Choose your path.',
    opts:[
      { t:'Provide the full impurity and stability documentation, item by item.', r:'win', why:'Winning Strategy. Complete documentation answers the Analytical objection.' },
      { t:'Tell her the profile is "standard" and to trust the brand.',    r:'escalate', why:'Trust-me ignores her drive for certainty.' },
      { t:'Point out that other QA teams approved it already.',            r:'escalate', why:'Social proof doesn\'t satisfy a documentation-driven mind.' },
    ]},
  { id:217, style:'expressive', name:'Dr. Nabil · Cardiologist (KOL)', crisis:'"The committee gave my symposium slot to someone else. Why bother with you?"',
    q:'Dr. Nabil (Expressive) feels slighted. Choose your path.',
    opts:[
      { t:'Recognize his standing and secure him a keynote and advisory platform.', r:'win', why:'Winning Strategy. Recognition and a stage feed the Expressive drive.' },
      { t:'Respond with the detailed terms of your current agreement.',    r:'escalate', why:'Spreadsheet-first deflates an Expressive.' },
      { t:'Downplay the symposium and ask him to stay loyal.',             r:'escalate', why:'Denying his standing escalates an Expressive.' },
    ]},
  { id:218, style:'amiable', name:'Noor · Community Pharmacist', crisis:'"An elderly customer got confused by the new packaging — I feel responsible."',
    q:'Noor (Amiable) feels guilty. Choose your path.',
    opts:[
      { t:'Acknowledge her care; provide a simple counseling card and ongoing support.', r:'win', why:'Winning Strategy. Empathy and a safety net satisfy the Amiable drive.' },
      { t:'Reassure her that sales are strong, so it\'s fine.',            r:'escalate', why:'Numbers don\'t address an Amiable\'s care concern.' },
      { t:'Tell her the packaging meets all regulations — not her problem.', r:'escalate', why:'Dismissing her feeling breaks Amiable trust.' },
    ]},
  { id:219, style:'driver', name:'Dr. Majed · Gastroenterologist', crisis:'"I have a full endoscopy list. You get 30 seconds — why should I switch?"',
    q:'Dr. Majed (Driver) is rushed. Choose your path.',
    opts:[
      { t:'One-line outcome benefit, two protocol options, his call.',     r:'win', why:'Winning Strategy. Brevity, options and control feed the Driver drive.' },
      { t:'Open the full clinical background to make your case.',          r:'escalate', why:'Long detail with no decision point frustrates a rushed Driver.' },
      { t:'Ask how his packed list is treating him this week.',           r:'escalate', why:'A Driver reads small talk as wasted time.' },
    ]},
  { id:220, style:'analytical', name:'Dr. Sana · Neurologist', crisis:'"Your relapse-rate claim has no comparator arm. I can\'t act on that."',
    q:'Dr. Sana (Analytical) wants proof. Choose your path.',
    opts:[
      { t:'Walk through the head-to-head data and the comparator arm precisely.', r:'win', why:'Winning Strategy. Rigorous evidence satisfies the Analytical drive for certainty.' },
      { t:'Argue the result speaks for itself without the comparison.',     r:'escalate', why:'An unsupported claim ignores her need for accuracy.' },
      { t:'Point out that leading centers already use it.',                r:'escalate', why:'Social proof isn\'t evidence for an Analytical.' },
    ]},
  { id:221, style:'amiable', name:'Dr. Rana · OB-GYN', crisis:'"I\'m anxious about using anything new in my pregnant patients."',
    q:'Dr. Rana (Amiable) is worried. Choose your path.',
    opts:[
      { t:'Acknowledge it; share the safety data and propose a careful, monitored start with your support.', r:'win', why:'Winning Strategy. A safe, supported path satisfies the Amiable drive for security.' },
      { t:'Push her to adopt now to keep pace with peers.',                r:'escalate', why:'Pressure attacks the Amiable need for security; stress rises.' },
      { t:'Tell her the efficacy data settles any worry.',                r:'escalate', why:'Data alone doesn\'t reassure an anxious Amiable.' },
    ]},
  { id:222, style:'expressive', name:'Dr. Adel · Sports Medicine', crisis:'"My clinic posted my new protocol and it barely got noticed. I feel ignored."',
    q:'Dr. Adel (Expressive) feels deflated. Choose your path.',
    opts:[
      { t:'Recognize his innovation and co-build a visible case-series showcase together.', r:'win', why:'Winning Strategy. Recognition plus a fresh idea restore the Expressive drive.' },
      { t:'Send him an analytics breakdown of why engagement was low.',    r:'escalate', why:'Cold analysis deflates an Expressive who wants to be seen.' },
      { t:'Tell him online attention doesn\'t matter — focus on the work.', r:'escalate', why:'Dismissing his standing escalates an Expressive.' },
    ]},
  { id:223, style:'driver', name:'Basel · Distributor Buyer', crisis:'"Your last shipment was short and late. Give me one reason to keep ordering."',
    q:'Basel (Driver) is unimpressed. Choose your path.',
    opts:[
      { t:'Offer two supply-guarantee options with the cost impact, his call.', r:'win', why:'Winning Strategy. Action, options and control feed the Driver drive.' },
      { t:'Apologize at length for the supply problem.',                   r:'escalate', why:'Dwelling on the past reads as no progress to a Driver.' },
      { t:'Lean on your long-standing partnership.',                       r:'escalate', why:'A Driver wants the fix, not sentiment.' },
    ]},
  { id:224, style:'analytical', name:'Dr. Faisal · Ophthalmologist', crisis:'"Your IOP-reduction figures aren\'t broken down by baseline pressure. I can\'t prescribe blind."',
    q:'Dr. Faisal (Analytical) needs detail. Choose your path.',
    opts:[
      { t:'Show the IOP data stratified by baseline, subgroup by subgroup.', r:'win', why:'Winning Strategy. Precise, segmented data resolves the Analytical objection.' },
      { t:'Reassure him the average reduction is "more than enough."',     r:'escalate', why:'Vague averages ignore his drive for accuracy.' },
      { t:'Say most ophthalmologists don\'t need that breakdown.',         r:'escalate', why:'Dismissing his question raises an Analytical\'s stress.' },
    ]},
  { id:225, style:'amiable', name:'Dr. Lama · Palliative Care', crisis:'"Adding another drug for my fragile patients really worries me."',
    q:'Dr. Lama (Amiable) is anxious. Choose your path.',
    opts:[
      { t:'Acknowledge it; offer a gentle low-dose start with monitoring and your support.', r:'win', why:'Winning Strategy. A safe, supported path satisfies the Amiable drive for security.' },
      { t:'Push her to hit the adoption target this cycle.',              r:'escalate', why:'Pressure attacks the Amiable need for security.' },
      { t:'Tell her the tolerability data means there\'s nothing to fear.', r:'escalate', why:'Data alone doesn\'t calm an anxious Amiable.' },
    ]},
  { id:226, style:'expressive', name:'Dr. Dina · Endocrinologist (KOL)', crisis:'"Another company offered to make me the face of their program. Why stay with you?"',
    q:'Dr. Dina (Expressive) is courting offers. Choose your path.',
    opts:[
      { t:'Recognize her influence and offer a visible platform — a symposium and program lead role.', r:'win', why:'Winning Strategy. Recognition and a stage feed the Expressive drive.' },
      { t:'Counter with detailed, cold contract terms.',                  r:'escalate', why:'Spreadsheet-first deflates an Expressive who wants to be seen.' },
      { t:'Downplay the rival and ask her to stay out of loyalty.',       r:'escalate', why:'Denying her standing escalates an Expressive.' },
    ]},
  { id:227, style:'driver', name:'Tariq · Pharmacy Owner', crisis:'"The generic is half your price. Give me a number, not a story."',
    q:'Tariq (Driver) wants it fast. Choose your path.',
    opts:[
      { t:'Lead with margin and turnover, give two pack options, his call.', r:'win', why:'Winning Strategy. Numbers, options and a fast decision feed the Driver drive.' },
      { t:'Deliver a lecture on why the brand is clinically superior.',    r:'escalate', why:'A time-pressed Driver reads this as wasted time.' },
      { t:'Ask how he feels about stocking premium quality.',             r:'escalate', why:'A Driver wants the number, not a feelings question.' },
    ]},
  // ── Iraq pack ──
  { id:1201, style:'driver', name:'Dr. Haider · Cardiologist', crisis:'"Your product vanished from the warehouse for two months and I lost patients to the competitor. Why trust your supply?"',
    q:'Dr. Haider (Driver) is angry. Choose your path.',
    opts:[
      { t:'Acknowledge it briefly, then give a concrete supply guarantee and two options, his call.', r:'win', why:'Winning Strategy. Action, options and control feed the Driver drive for Control & Achievement.' },
      { t:'Apologize at length for the supply gap.', r:'escalate', why:'Dwelling on the past reads as no progress to a Driver.' },
      { t:'Lean on your long relationship and ask him to be patient.', r:'escalate', why:'A Driver reads patience as no progress on the problem.' },
    ]},
  { id:1202, style:'analytical', name:'Dr. Zainab · Endocrinologist', crisis:'"A competitor rep was here yesterday with data saying yours is no better. Convince me or don\'t waste my time."',
    q:'Dr. Zainab (Analytical) is challenging you. Choose your path.',
    opts:[
      { t:'Walk through the head-to-head endpoints and number-needed-to-treat, calmly.', r:'win', why:'Winning Strategy. Evidence and a logical breakdown satisfy the Analytical drive for Certainty & Accuracy.' },
      { t:'Insist your drug is simply better and ask her to trust your experience.', r:'escalate', why:'Dismissing data raises an Analytical\'s stress and erodes trust.' },
      { t:'Appeal emotionally to your long relationship.', r:'escalate', why:'Emotion over evidence ignores what an Analytical needs.' },
    ]},
  { id:1203, style:'amiable', name:'Abu Ahmed · Community Pharmacist', crisis:'"A customer came back complaining of side effects — I\'m nervous to recommend it again."',
    q:'Abu Ahmed (Amiable) is worried. Choose your path.',
    opts:[
      { t:'Acknowledge the concern, share the safety profile and a patient-counseling card, and offer support.', r:'win', why:'Winning Strategy. Reassurance and a safety net satisfy the Amiable drive for Security & Harmony.' },
      { t:'Push him to keep ordering — one complaint is nothing.', r:'escalate', why:'Pressure attacks the Amiable need for security; stress spikes.' },
      { t:'Tell him the data says it\'s fine and move on.', r:'escalate', why:'Data alone doesn\'t reassure an Amiable.' },
    ]},
  { id:1204, style:'expressive', name:'Dr. Mustafa · Dermatologist', crisis:'"The conference committee gave my session to someone else. I feel ignored."',
    q:'Dr. Mustafa (Expressive) is deflated. Choose your path.',
    opts:[
      { t:'Recognize his standing, then co-build the next case series or symposium together.', r:'win', why:'Winning Strategy. Recognition plus fresh ideas restore the Expressive drive for Recognition & Ideas.' },
      { t:'Send him a chart explaining why the approach underperformed.', r:'escalate', why:'Cold analysis deflates an Expressive.' },
      { t:'Tell him to toughen up and not take it personally.', r:'escalate', why:'Denying recognition escalates an Expressive fast.' },
    ]},
  { id:1205, style:'driver', name:'Hajji Salam · Pharmacy Owner', crisis:'"The imported generic is half your price. Give me a reason in ten seconds, not a story."',
    q:'Hajji Salam (Driver) wants it fast. Choose your path.',
    opts:[
      { t:'Lead with margin and turnover, give two pack options, his call.', r:'win', why:'Winning Strategy. Numbers, options and a fast decision feed the Driver drive.' },
      { t:'Deliver a lecture on why the brand is clinically superior.', r:'escalate', why:'A time-pressed Driver reads this as wasted time.' },
      { t:'Ask how he feels about stocking premium quality.', r:'escalate', why:'A Driver wants the number, not a feelings question.' },
    ]},
  { id:1206, style:'analytical', name:'Hassan · Hospital Pharmacist', crisis:'"Your stability data doesn\'t cover our summer storage — Baghdad hits 50°C. I can\'t list it."',
    q:'Hassan (Analytical) has blocked the listing. Choose your path.',
    opts:[
      { t:'Go through the stability dossier and your storage range point by point.', r:'win', why:'Winning Strategy. Precision on the exact data resolves the Analytical objection.' },
      { t:'Reassure him vaguely that it will be fine.', r:'escalate', why:'Vague comfort ignores his drive for certainty.' },
      { t:'Point out that other hospitals listed it, so he should too.', r:'escalate', why:'Social proof doesn\'t answer an Analytical\'s data question.' },
    ]},
  { id:1207, style:'amiable', name:'Dr. Noor · Family GP', crisis:'"You\'re pushing me to switch all my patients at once — I\'m not comfortable."',
    q:'Dr. Noor (Amiable) feels pressured. Choose your path.',
    opts:[
      { t:'Reassure her; propose switching only new patients first, with your support.', r:'win', why:'Winning Strategy. A low-risk phased path satisfies the Amiable drive for security.' },
      { t:'Push for a full switch now to hit the cycle target.', r:'escalate', why:'Pressure attacks the Amiable need for security; stress rises.' },
      { t:'Tell her the data proves it\'s safe, so she should just do it.', r:'escalate', why:'Data alone doesn\'t reassure an Amiable under pressure.' },
    ]},
  { id:1208, style:'expressive', name:'Dr. Sajjad · Orthopedic Surgeon (KOL)', crisis:'"Another company offered me a bigger speaking role. Why should I stay with you?"',
    q:'Dr. Sajjad (Expressive) is courting offers. Choose your path.',
    opts:[
      { t:'Recognize his influence and offer a visible platform for his ideas — a symposium and advisory role.', r:'win', why:'Winning Strategy. Recognition and a stage feed the Expressive drive.' },
      { t:'Counter with cold, detailed contract terms.', r:'escalate', why:'Spreadsheet-first deflates an Expressive who wants to be seen.' },
      { t:'Downplay the competitor and ask him to stay out of loyalty.', r:'escalate', why:'Denying his standing escalates an Expressive.' },
    ]},
]

// ───────────────────────── LEVEL 3 · Drive Decoder (pool of 27) ─────────────────────────
export const L3: L3Item[] = [
  { id:301, multi:false, style:'driver', name:'Dr. Khalid · Surgeon', persona:'Driver — drive: Control & Achievement',
    situation:'Dr. Khalid is calm but has 5 minutes before his next case.',
    q:'Which opening best feeds his core drive?',
    opts:[
      { t:'"Two regimens that cut your patients\' recovery time, with the outcome data on each — your call."', correct:true, why:'Control + measurable achievement. Exactly the Driver drive.' },
      { t:'"Let me walk you through the full development story first."', correct:false, why:'Process narrative drains a Driver who wants control of the outcome.' },
      { t:'"How was your weekend? Let\'s catch up first."',             correct:false, why:'Relationship warmth is the Amiable drive, not the Driver\'s.' },
    ]},
  { id:302, multi:false, style:'expressive', name:'Dr. Hana · Dermatologist', persona:'Expressive — drive: Recognition & Ideas',
    situation:'Dr. Hana is pitching you her idea to run a local case series.',
    q:'Which response best feeds her core drive?',
    opts:[
      { t:'"Bold, original — let\'s build it and put your name on the publication."', correct:true, why:'Recognition + room for ideas. The Expressive drive.' },
      { t:'"Could you send me the supporting data tables first?"',      correct:false, why:'That satisfies an Analytical, not an Expressive who wants to be seen.' },
      { t:'"Let\'s slow down and reduce the risk before anything."',    correct:false, why:'Caution speaks to the Amiable drive and deflates the Expressive.' },
    ]},
  { id:303, multi:false, style:'amiable', name:'Dr. Mona · Family GP', persona:'Amiable — drive: Security & Harmony',
    situation:'Dr. Mona likes you but hasn\'t committed to prescribing.',
    q:'Which response best feeds her core drive?',
    opts:[
      { t:'"We\'ll start with a few new patients, I\'ll support you personally, and we can pause anytime."', correct:true, why:'Security + harmony with a safety net. The Amiable drive.' },
      { t:'"Decide today — the launch offer expires tonight."',         correct:false, why:'Urgency threatens an Amiable\'s need for security.' },
      { t:'"The trial numbers are airtight, that should settle it."',   correct:false, why:'Data reassures an Analytical, not an Amiable.' },
    ]},
  { id:304, multi:false, style:'analytical', name:'Fadi · Hospital Pharmacist', persona:'Analytical — drive: Certainty & Accuracy',
    situation:'Fadi is deciding whether to add your drug to the formulary.',
    q:'Which response best feeds his core drive?',
    opts:[
      { t:'"Here\'s the full trial dossier and stability data matched to your storage conditions."', correct:true, why:'Evidence and precision. The Analytical drive.' },
      { t:'"Everyone\'s listing it — you don\'t want to be last."',     correct:false, why:'Social pressure doesn\'t answer a certainty-driven mind.' },
      { t:'"Let\'s just trial it informally and see what happens."',    correct:false, why:'Improvising undermines an Analytical\'s need for rigor.' },
    ]},
  { id:305, multi:false, style:'analytical', name:'Dr. Salim · Cardiologist', persona:'Analytical — drive: Certainty & Accuracy',
    situation:'Dr. Salim is skeptical and evaluating the evidence.',
    q:'Which response best feeds his core drive?',
    opts:[
      { t:'"Here\'s the head-to-head RCT: primary endpoint, and the number needed to treat."', correct:true, why:'Rigorous evidence. The Analytical drive.' },
      { t:'"It\'s the market leader — that says enough."',              correct:false, why:'Market position isn\'t clinical proof.' },
      { t:'"All my other cardiologists already love it."',             correct:false, why:'Anecdote doesn\'t satisfy an evidence-driven specialist.' },
    ]},
  { id:306, multi:false, style:'driver', name:'Ziad · Pharmacy Owner', persona:'Driver — drive: Control & Achievement',
    situation:'Ziad is deciding whether to stock your product.',
    q:'Which response best feeds his core drive?',
    opts:[
      { t:'"Two pack sizes — here\'s the margin and turnover on each. Pick what fits."', correct:true, why:'Numbers, options and control. The Driver drive.' },
      { t:'"Let me explain the science behind the formulation."',       correct:false, why:'Mechanism detail bores a results-focused Driver.' },
      { t:'"It\'ll build patient loyalty over the years."',            correct:false, why:'Slow, soft benefit doesn\'t move a Driver who wants the number now.' },
    ]},
  { id:307, multi:false, style:'expressive', name:'Dr. Yousef · Psychiatrist (KOL)', persona:'Expressive — drive: Recognition & Ideas',
    situation:'Dr. Yousef wants to be at the front of a new treatment trend.',
    q:'Which response best feeds his core drive?',
    opts:[
      { t:'"Let\'s put you on the symposium panel to share your early experience."', correct:true, why:'Recognition + a stage for his ideas. The Expressive drive.' },
      { t:'"First, please complete this detailed audit form."',         correct:false, why:'Paperwork-first deflates an Expressive.' },
      { t:'"Best to wait until everyone else has adopted it."',         correct:false, why:'Caution kills the Expressive\'s appetite to be first.' },
    ]},
  { id:308, multi:false, style:'amiable', name:'Dr. Layla · Pediatrician', persona:'Amiable — drive: Security & Harmony',
    situation:'Dr. Layla is cautious about using it in children.',
    q:'Which response best feeds her core drive?',
    opts:[
      { t:'"Here\'s the pediatric safety data; start with a few patients and I\'ll be reachable anytime."', correct:true, why:'Safety + a supported, gradual path. The Amiable drive.' },
      { t:'"You\'re behind your peers — start prescribing widely now."', correct:false, why:'Pressure threatens the Amiable need for security.' },
      { t:'"The efficacy numbers are excellent, that\'s all you need."', correct:false, why:'Efficacy data alone doesn\'t calm a safety-first Amiable.' },
    ]},
  { id:309, multi:true, name:'Formulary mini-board: Fadi + Dr. Yousef', persona:'Multi-stakeholder — competing drives',
    situation:'Analytical pharmacist Fadi wants proof; Expressive KOL Dr. Yousef wants his approach recognized. Both are in the room.',
    q:'Which single move best balances BOTH drives at once?',
    opts:[
      { t:'"Dr. Yousef\'s approach leads the case — and here\'s the evidence dossier that backs it for the formulary."', correct:true, why:'Recognition for Yousef (Expressive) + evidence for Fadi (Analytical). Both drives met.' },
      { t:'"Let\'s champion the exciting approach now and sort the data later."', correct:false, why:'Pleases Yousef but ignores Fadi\'s drive for certainty.' },
      { t:'"We\'ll only move once every figure is triple-checked."',     correct:false, why:'Satisfies Fadi but starves Yousef\'s need for recognition.' },
    ]},
  { id:310, multi:true, name:'Pharmacy chain meeting: Sara + Huda', persona:'Multi-stakeholder — competing drives',
    situation:'Driver buyer Sara wants the numbers; Amiable pharmacist Huda wants her customers cared for. Both must agree.',
    q:'Which single move best balances BOTH drives at once?',
    opts:[
      { t:'"Best terms for your turnover targets — plus a counseling guide so your pharmacists keep customers safe and loyal."', correct:true, why:'Margin/turnover for Sara (Driver) + patient-care security for Huda (Amiable). Both drives met.' },
      { t:'"Let\'s focus purely on price and volume today."',           correct:false, why:'Wins Sara but ignores Huda\'s care-and-trust drive.' },
      { t:'"Let\'s center everything on patient stories and relationships."', correct:false, why:'Warms Huda but starves Sara\'s need for the numbers.' },
    ]},
  { id:311, multi:false, style:'driver', name:'Dr. Hadi · Clinic Owner (GP)', persona:'Driver — drive: Control & Achievement',
    situation:'Dr. Hadi runs a packed clinic and is sizing you up between patients.',
    q:'Which opening best feeds his core drive?',
    opts:[
      { t:'"Two regimens that move your patients through faster, with the throughput data — your call."', correct:true, why:'Control + measurable achievement. The Driver drive.' },
      { t:'"Let me give you the full clinical background first."', correct:false, why:'Process narrative drains a results-focused Driver.' },
      { t:'"How\'s the family? Let\'s catch up."',                 correct:false, why:'Relationship warmth is the Amiable drive.' },
    ]},
  { id:312, multi:false, style:'analytical', name:'Dr. Tamer · Infectious Disease', persona:'Analytical — drive: Certainty & Accuracy',
    situation:'Dr. Tamer is weighing your antibiotic against resistance data.',
    q:'Which response best feeds his core drive?',
    opts:[
      { t:'"Here are the local resistance rates and MIC values versus the comparator."', correct:true, why:'Rigorous evidence. The Analytical drive.' },
      { t:'"It\'s the most prescribed in its class."',            correct:false, why:'Popularity isn\'t proof.' },
      { t:'"Most ID colleagues have already switched."',          correct:false, why:'Anecdote doesn\'t satisfy an Analytical.' },
    ]},
  { id:313, multi:false, style:'expressive', name:'Dr. Nabil · Cardiologist (KOL)', persona:'Expressive — drive: Recognition & Ideas',
    situation:'Dr. Nabil wants to lead the conversation on a new approach.',
    q:'Which response best feeds his core drive?',
    opts:[
      { t:'"Let\'s put you on the regional symposium to present your early results."', correct:true, why:'Recognition + a platform. The Expressive drive.' },
      { t:'"First, complete this detailed data-entry form."',     correct:false, why:'Paperwork-first deflates an Expressive.' },
      { t:'"Better to wait until the guidelines catch up."',      correct:false, why:'Caution kills the Expressive\'s drive to lead.' },
    ]},
  { id:314, multi:false, style:'amiable', name:'Dr. Maha · Pediatric GP', persona:'Amiable — drive: Security & Harmony',
    situation:'Dr. Maha is cautious about prescribing for her young patients.',
    q:'Which response best feeds her core drive?',
    opts:[
      { t:'"Here\'s the pediatric safety data; start with a few patients and I\'m always reachable."', correct:true, why:'Safety + a supported path. The Amiable drive.' },
      { t:'"You\'re behind your peers — prescribe broadly now."', correct:false, why:'Pressure threatens the Amiable need for security.' },
      { t:'"The efficacy is excellent, that settles it."',        correct:false, why:'Efficacy alone doesn\'t calm a safety-first Amiable.' },
    ]},
  { id:315, multi:false, style:'driver', name:'Lina · Hospital Procurement', persona:'Driver — drive: Control & Achievement',
    situation:'Lina is deciding which supplier wins the contract.',
    q:'Which response best feeds her core drive?',
    opts:[
      { t:'"Two contract options — here\'s the price and delivery guarantee on each. Your pick."', correct:true, why:'Numbers, options and control. The Driver drive.' },
      { t:'"Let me tell you about our company\'s history."',      correct:false, why:'Heritage story bores a results-focused Driver.' },
      { t:'"We\'ll build a great partnership over time."',         correct:false, why:'Slow relationship talk won\'t move a Driver who wants terms now.' },
    ]},
  { id:316, multi:false, style:'analytical', name:'Dr. Samira · Nephrologist', persona:'Analytical — drive: Certainty & Accuracy',
    situation:'Dr. Samira is evaluating renal safety before prescribing.',
    q:'Which response best feeds her core drive?',
    opts:[
      { t:'"Here\'s the renal-impairment dosing study with clearance data by stage."', correct:true, why:'Precise evidence. The Analytical drive.' },
      { t:'"It\'s widely used, so it\'s safe."',                  correct:false, why:'Usage isn\'t renal-safety proof.' },
      { t:'"Trust me, the dose is fine."',                        correct:false, why:'Trust-me undermines an Analytical\'s need for rigor.' },
    ]},
  { id:317, multi:false, style:'amiable', name:'Noor · Community Pharmacist', persona:'Amiable — drive: Security & Harmony',
    situation:'Noor likes you but hasn\'t committed to stocking it.',
    q:'Which response best feeds her core drive?',
    opts:[
      { t:'"We\'ll start small, I\'ll give you a counseling guide for your customers, and you reorder only if it helps them."', correct:true, why:'Security + customer care with a safety net. The Amiable drive.' },
      { t:'"Order a full case now — the deal ends today."',       correct:false, why:'Urgency threatens an Amiable\'s need for security.' },
      { t:'"The margins are great, that\'s the main thing."',     correct:false, why:'Margin-first speaks to a Driver, not an Amiable.' },
    ]},
  { id:318, multi:true, name:'Hospital tender: Lina + Mariam', persona:'Multi-stakeholder — competing drives',
    situation:'Driver procurement officer Lina wants price and speed; Analytical quality pharmacist Mariam wants complete documentation. Both must sign off.',
    q:'Which single move best balances BOTH drives at once?',
    opts:[
      { t:'"Here\'s our best price with a delivery guarantee — and the full documentation pack your QA needs to approve it."', correct:true, why:'Price/speed for Lina (Driver) + documentation for Mariam (Analytical). Both drives met.' },
      { t:'"Let\'s lock the price today and sort the paperwork later."', correct:false, why:'Wins Lina but ignores Mariam\'s need for certainty.' },
      { t:'"We\'ll wait until every document is triple-checked before talking terms."', correct:false, why:'Satisfies Mariam but starves Lina\'s need for a fast deal.' },
    ]},
  { id:319, multi:false, style:'driver', name:'Dr. Majed · Gastroenterologist', persona:'Driver — drive: Control & Achievement',
    situation:'Dr. Majed is sizing you up between endoscopy cases.',
    q:'Which opening best feeds his core drive?',
    opts:[
      { t:'"Two protocols that move your list faster, with the throughput data — your call."', correct:true, why:'Control + measurable achievement. The Driver drive.' },
      { t:'"Let me first take you through the full mechanism of action."', correct:false, why:'Process detail drains a results-focused Driver.' },
      { t:'"How has the family been? Let\'s catch up."',                correct:false, why:'Relationship warmth is the Amiable drive.' },
    ]},
  { id:320, multi:false, style:'analytical', name:'Dr. Sana · Neurologist', persona:'Analytical — drive: Certainty & Accuracy',
    situation:'Dr. Sana is weighing your therapy against the comparator.',
    q:'Which response best feeds her core drive?',
    opts:[
      { t:'"Here\'s the head-to-head trial: primary endpoint, relapse rate, and the comparator arm."', correct:true, why:'Rigorous evidence. The Analytical drive.' },
      { t:'"It\'s the fastest-growing option in its class."',          correct:false, why:'Popularity isn\'t proof.' },
      { t:'"Most neurologists have already switched."',                correct:false, why:'Anecdote doesn\'t satisfy an Analytical.' },
    ]},
  { id:321, multi:false, style:'expressive', name:'Dr. Adel · Sports Medicine', persona:'Expressive — drive: Recognition & Ideas',
    situation:'Dr. Adel wants to be first with a talked-about approach.',
    q:'Which response best feeds his core drive?',
    opts:[
      { t:'"Let\'s put you on the panel to present your early results and put your name on it."', correct:true, why:'Recognition + a stage for his ideas. The Expressive drive.' },
      { t:'"First, please complete this detailed audit form."',        correct:false, why:'Paperwork-first deflates an Expressive.' },
      { t:'"Best to wait until everyone else adopts it."',             correct:false, why:'Caution kills the Expressive\'s drive to be first.' },
    ]},
  { id:322, multi:false, style:'amiable', name:'Dr. Rana · OB-GYN', persona:'Amiable — drive: Security & Harmony',
    situation:'Dr. Rana is cautious about using it in pregnancy.',
    q:'Which response best feeds her core drive?',
    opts:[
      { t:'"Here\'s the safety data; start with a few patients you know and I\'ll be reachable anytime."', correct:true, why:'Safety + a supported, gradual path. The Amiable drive.' },
      { t:'"You\'re behind your peers — start prescribing widely now."', correct:false, why:'Pressure threatens the Amiable need for security.' },
      { t:'"The efficacy numbers are excellent, that\'s all you need."', correct:false, why:'Efficacy alone doesn\'t calm a safety-first Amiable.' },
    ]},
  { id:323, multi:false, style:'analytical', name:'Dr. Faisal · Ophthalmologist', persona:'Analytical — drive: Certainty & Accuracy',
    situation:'Dr. Faisal is evaluating the pressure-lowering evidence.',
    q:'Which response best feeds his core drive?',
    opts:[
      { t:'"Here\'s the IOP reduction stratified by baseline pressure, with confidence intervals."', correct:true, why:'Precise, segmented evidence. The Analytical drive.' },
      { t:'"Trust me, the effect is strong across the board."',        correct:false, why:'Trust-me undermines an Analytical\'s need for rigor.' },
      { t:'"It\'s the most prescribed drop in the region."',           correct:false, why:'Usage isn\'t clinical proof.' },
    ]},
  { id:324, multi:false, style:'expressive', name:'Dr. Dina · Endocrinologist (KOL)', persona:'Expressive — drive: Recognition & Ideas',
    situation:'Dr. Dina wants to champion a new patient-care program.',
    q:'Which response best feeds her core drive?',
    opts:[
      { t:'"Lead the program as its public face and co-design the rollout with us."', correct:true, why:'Recognition + room for her ideas. The Expressive drive.' },
      { t:'"Send me the supporting data tables first."',               correct:false, why:'That satisfies an Analytical, not an Expressive who wants to be seen.' },
      { t:'"Let\'s slow down and de-risk it before anything."',        correct:false, why:'Caution speaks to the Amiable drive and deflates the Expressive.' },
    ]},
  { id:325, multi:false, style:'amiable', name:'Dr. Lama · Palliative Care', persona:'Amiable — drive: Security & Harmony',
    situation:'Dr. Lama likes you but worries about her fragile patients.',
    q:'Which response best feeds her core drive?',
    opts:[
      { t:'"We\'ll start low and slow, I\'ll support you personally, and we can pause anytime."', correct:true, why:'Security + harmony with a safety net. The Amiable drive.' },
      { t:'"Decide today — the program enrollment closes tonight."',   correct:false, why:'Urgency threatens an Amiable\'s need for security.' },
      { t:'"The tolerability numbers are airtight, that should settle it."', correct:false, why:'Data reassures an Analytical, not an Amiable.' },
    ]},
  { id:326, multi:true, name:'Clinic decision: Dr. Majed + Dr. Lama', persona:'Multi-stakeholder — competing drives',
    situation:'Driver gastroenterologist Dr. Majed wants throughput; Amiable palliative physician Dr. Lama wants patient comfort. Both share the ward.',
    q:'Which single move best balances BOTH drives at once?',
    opts:[
      { t:'"A faster protocol to move your list — with a gentle low-dose path and monitoring so fragile patients stay comfortable."', correct:true, why:'Throughput for Majed (Driver) + safe comfort for Lama (Amiable). Both drives met.' },
      { t:'"Let\'s optimize purely for speed and volume today."',      correct:false, why:'Wins Majed but ignores Lama\'s comfort-and-security drive.' },
      { t:'"Let\'s center everything on patient comfort and go slow."', correct:false, why:'Warms Lama but starves Majed\'s need for throughput.' },
    ]},
  { id:327, multi:true, name:'Launch meeting: Dr. Dina + Dr. Sana', persona:'Multi-stakeholder — competing drives',
    situation:'Expressive KOL Dr. Dina wants to champion the idea; Analytical neurologist Dr. Sana wants the comparator evidence. Both must be on board.',
    q:'Which single move best balances BOTH drives at once?',
    opts:[
      { t:'"Dr. Dina fronts the program — and here\'s the head-to-head evidence pack that backs it for the team."', correct:true, why:'Recognition for Dina (Expressive) + evidence for Sana (Analytical). Both drives met.' },
      { t:'"Let\'s launch the exciting program now and gather data later."', correct:false, why:'Pleases Dina but ignores Sana\'s drive for certainty.' },
      { t:'"We\'ll only move once every figure is triple-checked."',   correct:false, why:'Satisfies Sana but starves Dina\'s need for recognition.' },
    ]},
  // ── Iraq pack ──
  { id:1301, multi:false, style:'driver', name:'Dr. Haider · Cardiologist', persona:'Driver — drive: Control & Achievement',
    situation:'Dr. Haider is calm but has 5 minutes before his next patient in a packed Medical City clinic.',
    q:'Which opening best feeds his core drive?',
    opts:[
      { t:'"Two regimens that move your patients through faster, with the outcome data on each — your call."', correct:true, why:'Control + measurable achievement. The Driver drive.' },
      { t:'"Let me walk you through the full development story first."', correct:false, why:'Process narrative drains a Driver who wants control of the outcome.' },
      { t:'"How was your weekend? Let\'s catch up first."', correct:false, why:'Relationship warmth is the Amiable drive, not the Driver\'s.' },
    ]},
  { id:1302, multi:false, style:'expressive', name:'Dr. Mustafa · Dermatologist', persona:'Expressive — drive: Recognition & Ideas',
    situation:'Dr. Mustafa is pitching you his idea to run a local case series in Baghdad.',
    q:'Which response best feeds his core drive?',
    opts:[
      { t:'"Bold, original — let\'s build it and put your name on the publication."', correct:true, why:'Recognition + room for ideas. The Expressive drive.' },
      { t:'"Could you send me the supporting data tables first?"', correct:false, why:'That satisfies an Analytical, not an Expressive who wants to be seen.' },
      { t:'"Let\'s slow down and reduce the risk before anything."', correct:false, why:'Caution speaks to the Amiable drive and deflates the Expressive.' },
    ]},
  { id:1303, multi:false, style:'amiable', name:'Dr. Noor · Family GP', persona:'Amiable — drive: Security & Harmony',
    situation:'Dr. Noor likes you but hasn\'t committed to prescribing.',
    q:'Which response best feeds her core drive?',
    opts:[
      { t:'"We\'ll start with a few new patients, I\'ll support you personally, and we can pause anytime."', correct:true, why:'Security + harmony with a safety net. The Amiable drive.' },
      { t:'"Decide today — the launch offer expires tonight."', correct:false, why:'Urgency threatens an Amiable\'s need for security.' },
      { t:'"The trial numbers are airtight, that should settle it."', correct:false, why:'Data reassures an Analytical, not an Amiable.' },
    ]},
  { id:1304, multi:false, style:'analytical', name:'Hassan · Hospital Pharmacist', persona:'Analytical — drive: Certainty & Accuracy',
    situation:'Hassan is deciding whether to add your drug to the formulary.',
    q:'Which response best feeds his core drive?',
    opts:[
      { t:'"Here\'s the full trial dossier and stability data matched to your summer storage conditions."', correct:true, why:'Evidence and precision. The Analytical drive.' },
      { t:'"Everyone\'s listing it — you don\'t want to be last."', correct:false, why:'Social pressure doesn\'t answer a certainty-driven mind.' },
      { t:'"Let\'s just trial it informally and see what happens."', correct:false, why:'Improvising undermines an Analytical\'s need for rigor.' },
    ]},
  { id:1305, multi:false, style:'driver', name:'Hajji Salam · Pharmacy Owner', persona:'Driver — drive: Control & Achievement',
    situation:'Hajji Salam is deciding whether to stock your product.',
    q:'Which response best feeds his core drive?',
    opts:[
      { t:'"Two pack sizes — here\'s the margin and turnover on each. Pick what fits."', correct:true, why:'Numbers, options and control. The Driver drive.' },
      { t:'"Let me explain the science behind the formulation."', correct:false, why:'Mechanism detail bores a results-focused Driver.' },
      { t:'"It\'ll build patient loyalty over the years."', correct:false, why:'Slow, soft benefit doesn\'t move a Driver who wants the number now.' },
    ]},
  { id:1306, multi:false, style:'analytical', name:'Dr. Zainab · Endocrinologist', persona:'Analytical — drive: Certainty & Accuracy',
    situation:'Dr. Zainab is skeptical and weighing the evidence against a cheaper generic.',
    q:'Which response best feeds her core drive?',
    opts:[
      { t:'"Here\'s the head-to-head RCT: primary endpoint, and the number needed to treat."', correct:true, why:'Rigorous evidence. The Analytical drive.' },
      { t:'"It\'s the best-selling option in its class — that says enough."', correct:false, why:'Market position isn\'t clinical proof.' },
      { t:'"All my other endocrinologists already love it."', correct:false, why:'Anecdote doesn\'t satisfy an evidence-driven specialist.' },
    ]},
  { id:1307, multi:false, style:'amiable', name:'Abu Ahmed · Community Pharmacist', persona:'Amiable — drive: Security & Harmony',
    situation:'Abu Ahmed likes you but hasn\'t committed to stocking it.',
    q:'Which response best feeds his core drive?',
    opts:[
      { t:'"We\'ll start small, I\'ll give you a counseling guide for your customers, and you reorder only if it helps them."', correct:true, why:'Security + customer care with a safety net. The Amiable drive.' },
      { t:'"Order a full case now — the deal ends today."', correct:false, why:'Urgency threatens an Amiable\'s need for security.' },
      { t:'"The margins are great, that\'s the main thing."', correct:false, why:'Margin-first speaks to a Driver, not an Amiable.' },
    ]},
  { id:1308, multi:false, style:'expressive', name:'Dr. Sajjad · Orthopedic Surgeon (KOL)', persona:'Expressive — drive: Recognition & Ideas',
    situation:'Dr. Sajjad wants to be at the front of the conversation on a new technique.',
    q:'Which response best feeds his core drive?',
    opts:[
      { t:'"Let\'s put you on the regional symposium to present your early results."', correct:true, why:'Recognition + a stage for his ideas. The Expressive drive.' },
      { t:'"First, please complete this detailed data-entry form."', correct:false, why:'Paperwork-first deflates an Expressive.' },
      { t:'"Best to wait until the guidelines catch up."', correct:false, why:'Caution kills the Expressive\'s drive to lead.' },
    ]},
]

// ───────────────────────── LEVEL 4 · The Formulary Committee (pool of 21) ─────────────────────────
// You present your drug to a hospital Pharmacy & Therapeutics committee:
// Analytical pharmacist, Driver department head, Amiable nurse manager, Expressive KOL.
// Meters: Adoption (quota) · Trust (morale) · Risk.
export const L4: L4Item[] = [
  { id:401, q:'Opening move with the whole committee watching:',
    opts:[
      { t:'Lead with a bold innovation story, lightly backed by headline data.',      quota:+8,  morale:+10, risk:+12, why:'Energizes the KOL & department head, but thin data spikes Risk for the Analytical pharmacist.' },
      { t:'Present a measured case: evidence pack, cost-effectiveness, phased rollout.', quota:+10, morale:+6,  risk:-8,  why:'Balanced. Hits the cost and evidence needs while keeping Risk low.' },
      { t:'Spend the slot only building rapport and reassurance.',                     quota:-4,  morale:+12, risk:-2,  why:'The nurse manager warms to it; the department head sees no progress on adoption.' },
    ]},
  { id:402, q:'The Analytical pharmacist challenges your stability and evidence. You:',
    opts:[
      { t:'Open the dossier and walk the data line by line.',                          quota:+6,  morale:+4,  risk:-12, why:'Transparency satisfies the Analytical and cuts Risk sharply.' },
      { t:'Wave it off — "the innovation matters more than the fine print."',          quota:0,   morale:-8,  risk:+15, why:'Dismissing data alienates the pharmacist and inflates Risk.' },
      { t:'Promise to send the data later and push to a vote.',                        quota:+4,  morale:-2,  risk:+8,  why:'Buys momentum but unresolved data keeps Risk elevated.' },
    ]},
  { id:403, q:'The Amiable nurse manager worries staff can\'t absorb the protocol change. You:',
    opts:[
      { t:'Bulldoze: "The protocol is set, they\'ll adapt."',                          quota:+10, morale:-16, risk:+6,  why:'Short-term push, but Trust collapses and the Amiable turns against you.' },
      { t:'Add a phased rollout with training and support — same protocol, safer path.', quota:+6,  morale:+12, risk:-6,  why:'Protects Trust and safety while still advancing Adoption.' },
      { t:'Drop the protocol change entirely to avoid friction.',                      quota:-10, morale:+6,  risk:-4,  why:'Harmony at the cost of the committee\'s adoption goal.' },
    ]},
  { id:404, q:'The Driver department head demands the cost decision now. You:',
    opts:[
      { t:'Offer two cost-effective options with a clear recommendation.',            quota:+14, morale:+6,  risk:-4,  why:'Decisive + evidenced. Lands the Driver without spooking the others.' },
      { t:'Ask for another month to align everyone.',                                 quota:-8,  morale:+4,  risk:-2,  why:'A Driver reads delay as failure — Adoption momentum is lost.' },
      { t:'Close hard on price alone, skipping the rationale.',                        quota:+6,  morale:-6,  risk:+10, why:'May win the moment but leaves the others uneasy — Risk climbs.' },
    ]},
  { id:405, q:'The Expressive KOL wants to champion the drug publicly. You:',
    opts:[
      { t:'Give him a visible role and co-author the rollout protocol.',              quota:+12, morale:+8,  risk:-2,  why:'Recognition turns him into your advocate, lifting Adoption and Trust.' },
      { t:'Tell him to keep it low-key for now.',                                     quota:-2,  morale:-8,  risk:+2,  why:'Denying the stage deflates the Expressive and cools the room.' },
      { t:'Ignore him and stay focused on the numbers.',                             quota:+4,  morale:-4,  risk:+4,  why:'Missing his recognition need costs you a champion.' },
    ]},
  { id:406, q:'The budget holder flags your price versus the generic. You:',
    opts:[
      { t:'Show total cost-of-care evidence — fewer admissions and complications.',   quota:+10, morale:+4,  risk:-10, why:'Reframes price as value with data; lowers Risk and advances Adoption.' },
      { t:'Argue it\'s premium and simply worth it, with no figures.',                quota:+2,  morale:-6,  risk:+10, why:'Assertion without evidence raises Risk for the committee.' },
      { t:'Offer a deep discount that undercuts your value story.',                   quota:+6,  morale:+2,  risk:+6,  why:'Buys a little adoption but signals the price was never real — Risk rises.' },
    ]},
  { id:407, q:'A safety signal from a competitor is raised in the room. You:',
    opts:[
      { t:'Present the safety registry transparently and put the signal in context.', quota:+6,  morale:+6,  risk:-12, why:'Openness builds Trust and cuts Risk hardest.' },
      { t:'Dismiss the competitor\'s claim as a smear.',                              quota:+2,  morale:-6,  risk:+12, why:'Defensiveness reads as hiding something — Risk spikes.' },
      { t:'Deflect with "the regulator approved it, end of story."',                  quota:+4,  morale:-2,  risk:+6,  why:'Approval isn\'t the same as engaging the concern — unease lingers.' },
    ]},
  { id:408, q:'The final vote moment. Your closing move:',
    opts:[
      { t:'Summarize evidence, cost and safety, and ask for adoption with a monitored pilot.', quota:+14, morale:+8,  risk:-6,  why:'Decisive, evidenced and low-risk — the apex close.' },
      { t:'Push hard for full immediate adoption across the hospital.',               quota:+8,  morale:-6,  risk:+10, why:'Over-reach unsettles the cautious members — Risk climbs.' },
      { t:'Withdraw and ask to revisit next quarter.',                               quota:-10, morale:+4,  risk:-4,  why:'Avoids friction but surrenders all Adoption momentum.' },
    ]},
  { id:409, q:'A rival rep spoke right before you and over-promised on outcomes. Your move:',
    opts:[
      { t:'Set realistic, data-backed expectations and let the contrast speak.',     quota:+10, morale:+6,  risk:-8,  why:'Credibility lowers Risk and quietly outclasses the over-promise.' },
      { t:'Match their bold claims to stay competitive.',                            quota:+6,  morale:-4,  risk:+14, why:'Inflated claims spike Risk with the Analytical members.' },
      { t:'Attack the rival\'s pitch head-on.',                                       quota:+2,  morale:-6,  risk:+8,  why:'Mud-slinging reads as insecure — Trust drops.' },
    ]},
  { id:410, q:'The committee chair asks for real-world evidence, not just trials. You:',
    opts:[
      { t:'Present registry and real-world outcome data alongside the RCTs.',        quota:+10, morale:+6,  risk:-10, why:'Real-world evidence answers the chair directly and lowers Risk.' },
      { t:'Insist the randomized trials are all that should matter.',                quota:+2,  morale:-4,  risk:+8,  why:'Dismissing their request raises Risk and cools the room.' },
      { t:'Promise to gather real-world data later.',                                quota:+4,  morale:0,   risk:+4,  why:'Deferral leaves the question open — mild Risk.' },
    ]},
  { id:411, q:'The budget is cut 15% mid-meeting. You:',
    opts:[
      { t:'Offer a phased, tiered adoption that preserves value within the new budget.', quota:+10, morale:+6,  risk:-6,  why:'Flexibility keeps Adoption alive without sacrificing value.' },
      { t:'Hold firm on full price and volume.',                                     quota:-6,  morale:-4,  risk:+8,  why:'Rigidity loses Adoption and raises Risk.' },
      { t:'Slash your price to whatever fits.',                                       quota:+6,  morale:+2,  risk:+8,  why:'A panic discount signals the price was never real — Risk climbs.' },
    ]},
  { id:412, q:'A committee member had a bad past experience with your company. You:',
    opts:[
      { t:'Acknowledge it, show what has changed, and back it with current data.',   quota:+8,  morale:+8,  risk:-8,  why:'Owning the past rebuilds Trust and lowers Risk.' },
      { t:'Insist it was a different team and move on quickly.',                      quota:+2,  morale:-6,  risk:+6,  why:'Brushing it off keeps the distrust alive.' },
      { t:'Avoid the topic entirely.',                                               quota:0,   morale:-4,  risk:+8,  why:'The unaddressed grievance festers — Risk rises.' },
    ]},
  { id:413, q:'The pharmacist flags a cold-chain storage concern. You:',
    opts:[
      { t:'Present the stability data and your cold-chain support plan.',            quota:+8,  morale:+6,  risk:-12, why:'Evidence plus a support plan cuts Risk hardest.' },
      { t:'Say storage "shouldn\'t be a problem" in their facility.',                quota:+2,  morale:-4,  risk:+12, why:'Hand-waving a logistics risk spikes it for the pharmacist.' },
      { t:'Suggest they sort out storage themselves.',                               quota:-2,  morale:-6,  risk:+10, why:'Offloading the problem erodes Trust and raises Risk.' },
    ]},
  { id:414, q:'The nurse manager asks about the training burden for the new protocol. You:',
    opts:[
      { t:'Offer on-site in-service training and ready-made materials.',             quota:+8,  morale:+12, risk:-6,  why:'Removing the training burden wins the Amiable and lifts Trust.' },
      { t:'Tell her the protocol is simple enough to self-teach.',                   quota:+2,  morale:-8,  risk:+6,  why:'Dismissing the burden alienates the nurse manager.' },
      { t:'Say training isn\'t your responsibility.',                                quota:-2,  morale:-10, risk:+8,  why:'Refusing support collapses Trust.' },
    ]},
  { id:415, q:'A patient-advocacy member asks how the drug affects quality of life, not just endpoints. You:',
    opts:[
      { t:'Present patient-reported outcome data alongside the clinical endpoints.',  quota:+8,  morale:+8,  risk:-8,  why:'Answering the human question directly builds Trust and lowers Risk.' },
      { t:'Insist the hard endpoints are what really count.',                        quota:+2,  morale:-6,  risk:+6,  why:'Dismissing the question cools the room and raises Risk.' },
      { t:'Promise to look into quality-of-life data later.',                        quota:+4,  morale:0,   risk:+4,  why:'Deferral leaves the concern open — mild Risk.' },
    ]},
  { id:416, q:'The pharmacy committee pushes mandatory generic substitution. You:',
    opts:[
      { t:'Show the sub-population where your brand changes outcomes, and accept generics elsewhere.', quota:+10, morale:+6,  risk:-8,  why:'A targeted, reasonable position protects adoption where it matters and lowers Risk.' },
      { t:'Argue the brand should be protected across the board.',                   quota:-4,  morale:-4,  risk:+8,  why:'Over-reach reads as self-serving — Trust drops, Risk climbs.' },
      { t:'Concede fully and hope volume holds.',                                    quota:-8,  morale:+2,  risk:-2,  why:'Surrendering the case sacrifices adoption momentum.' },
    ]},
  { id:417, q:'The Driver department head wants a decision today; the Analytical pharmacist wants another month. You:',
    opts:[
      { t:'Propose a monitored 90-day pilot that starts now with a data review built in.', quota:+12, morale:+8,  risk:-6,  why:'Action for the Driver + a review gate for the Analytical. Both are served and Risk drops.' },
      { t:'Side with the department head and push for a full vote now.',             quota:+6,  morale:-6,  risk:+10, why:'Wins speed but the Analytical feels steam-rolled — Risk spikes.' },
      { t:'Side with the pharmacist and delay a month.',                            quota:-8,  morale:+2,  risk:-2,  why:'A Driver reads delay as failure — adoption momentum is lost.' },
    ]},
  { id:418, q:'The chair asks who will monitor safety after adoption. You:',
    opts:[
      { t:'Lay out a clear pharmacovigilance plan with defined roles and reporting.', quota:+8,  morale:+8,  risk:-12, why:'A concrete monitoring plan cuts Risk hardest and reassures the cautious members.' },
      { t:'Say the regulator already handles post-market safety.',                   quota:+2,  morale:-4,  risk:+8,  why:'Offloading the responsibility leaves the committee uneasy — Risk rises.' },
      { t:'Suggest the hospital sort out monitoring itself.',                        quota:-2,  morale:-6,  risk:+10, why:'Pushing the burden onto them erodes Trust.' },
    ]},
  { id:419, q:'A rival rep slashed their price to the committee minutes before your slot. You:',
    opts:[
      { t:'Hold your price and reframe on total cost-of-care evidence.',            quota:+10, morale:+6,  risk:-8,  why:'Value over a panic discount keeps credibility and lowers Risk.' },
      { t:'Match the rival\'s cut on the spot.',                                     quota:+6,  morale:0,   risk:+8,  why:'A reactive discount signals your price was never real — Risk climbs.' },
      { t:'Attack the rival\'s lowball as unsustainable.',                          quota:+2,  morale:-6,  risk:+8,  why:'Mud-slinging reads as insecure — Trust drops.' },
    ]},
  { id:420, q:'A member worries the reporting paperwork will overload the staff. You:',
    opts:[
      { t:'Offer a streamlined reporting template and on-site support to run it.',   quota:+8,  morale:+12, risk:-6,  why:'Removing the admin burden wins the Amiable members and lifts Trust.' },
      { t:'Tell them the paperwork is minimal and they\'ll manage.',                quota:+2,  morale:-8,  risk:+6,  why:'Dismissing the burden alienates the staff-facing members.' },
      { t:'Say reporting logistics aren\'t your concern.',                          quota:-2,  morale:-10, risk:+8,  why:'Refusing support collapses Trust.' },
    ]},
  { id:421, q:'The committee leans yes but wants a staged hospital-wide rollout. You:',
    opts:[
      { t:'Agree to a phased rollout with adoption milestones and a review at each stage.', quota:+12, morale:+8,  risk:-6,  why:'Decisive yet measured — secures adoption while keeping Risk low.' },
      { t:'Push for immediate full rollout to lock the win.',                       quota:+8,  morale:-6,  risk:+10, why:'Over-reach unsettles the cautious members — Risk climbs.' },
      { t:'Ask to revisit the rollout plan next quarter.',                          quota:-10, morale:+4,  risk:-4,  why:'Avoids friction but surrenders the adoption momentum you earned.' },
    ]},
  // ── Iraq pack ── (hospital P&T committee, Baghdad context)
  { id:1401, q:'Opening move before the Medical City P&T committee:',
    opts:[
      { t:'Lead with a bold "first in Iraq" innovation story, lightly backed by headline data.', quota:+8,  morale:+10, risk:+12, why:'Energizes the KOL, but thin data spikes Risk for the Analytical pharmacist.' },
      { t:'Present a measured case: evidence pack, cost in dinars, and a phased rollout.',        quota:+10, morale:+6,  risk:-8,  why:'Balanced. Meets cost and evidence needs while keeping Risk low.' },
      { t:'Spend the slot only building rapport.',                                                quota:-4,  morale:+12, risk:-2,  why:'Warmth without progress leaves the department head unconvinced on adoption.' },
    ]},
  { id:1402, q:'A committee member recalls your two-month stockout last year. You:',
    opts:[
      { t:'Acknowledge it, show your new supply guarantee and local stock plan, backed by figures.', quota:+10, morale:+8,  risk:-8,  why:'Owning the lapse with a concrete fix rebuilds Trust and lowers Risk.' },
      { t:'Insist it was the distributor\'s fault, not yours.',                                       quota:+2,  morale:-6,  risk:+8,  why:'Blame-shifting keeps the distrust alive — Risk rises.' },
      { t:'Avoid the topic and move straight to efficacy.',                                           quota:0,   morale:-4,  risk:+8,  why:'The unaddressed grievance festers.' },
    ]},
  { id:1403, q:'The Analytical pharmacist flags summer cold-chain storage. You:',
    opts:[
      { t:'Present stability data for high temperatures and your cold-chain support plan.', quota:+8,  morale:+6,  risk:-12, why:'Evidence plus a support plan cuts Risk hardest.' },
      { t:'Say storage "shouldn\'t be a problem" in Baghdad.',                              quota:+2,  morale:-4,  risk:+12, why:'Hand-waving a real logistics risk spikes it.' },
      { t:'Tell them to handle storage themselves.',                                        quota:-2,  morale:-6,  risk:+10, why:'Offloading the problem erodes Trust.' },
    ]},
  { id:1404, q:'The committee pushes mandatory generic substitution to save budget. You:',
    opts:[
      { t:'Show the sub-population where your brand changes outcomes; accept generics elsewhere.', quota:+10, morale:+6,  risk:-8,  why:'A targeted, reasonable position protects adoption where it matters and lowers Risk.' },
      { t:'Argue the brand should be protected across the board.',                                  quota:-4,  morale:-4,  risk:+8,  why:'Over-reach reads as self-serving.' },
      { t:'Concede fully and hope volume holds.',                                                   quota:-8,  morale:+2,  risk:-2,  why:'Surrendering the case sacrifices adoption momentum.' },
    ]},
  { id:1405, q:'The Driver department head demands the cost decision now, in dinars. You:',
    opts:[
      { t:'Offer two cost-effective options with a clear recommendation.', quota:+14, morale:+6,  risk:-4,  why:'Decisive + evidenced. Lands the Driver without spooking the others.' },
      { t:'Ask for another month to align everyone.',                      quota:-8,  morale:+4,  risk:-2,  why:'A Driver reads delay as failure — momentum is lost.' },
      { t:'Close hard on price alone, skipping the rationale.',            quota:+6,  morale:-6,  risk:+10, why:'May win the moment but leaves the others uneasy.' },
    ]},
  { id:1406, q:'The budget is cut 15% mid-meeting. You:',
    opts:[
      { t:'Offer a phased, tiered adoption that preserves value within the new budget.', quota:+10, morale:+6,  risk:-6,  why:'Flexibility keeps adoption alive without sacrificing value.' },
      { t:'Hold firm on full price and volume.',                                         quota:-6,  morale:-4,  risk:+8,  why:'Rigidity loses adoption and raises Risk.' },
      { t:'Slash your price to whatever fits.',                                          quota:+6,  morale:+2,  risk:+8,  why:'A panic discount signals the price was never real.' },
    ]},
  { id:1407, q:'The Expressive KOL wants to champion the drug at the Iraqi congress. You:',
    opts:[
      { t:'Give him a visible role and co-author the rollout protocol.', quota:+12, morale:+8,  risk:-2,  why:'Recognition turns him into your advocate, lifting Adoption and Trust.' },
      { t:'Tell him to keep it low-key for now.',                        quota:-2,  morale:-8,  risk:+2,  why:'Denying the stage deflates the Expressive.' },
      { t:'Ignore him and stay focused on the numbers.',                quota:+4,  morale:-4,  risk:+4,  why:'Missing his recognition need costs you a champion.' },
    ]},
  { id:1408, q:'The final vote. Your closing move:',
    opts:[
      { t:'Summarize evidence, dinar cost and safety, and ask for adoption with a monitored pilot.', quota:+14, morale:+8,  risk:-6,  why:'Decisive, evidenced and low-risk — the apex close.' },
      { t:'Push for full immediate adoption across the hospital.',                                   quota:+8,  morale:-6,  risk:+10, why:'Over-reach unsettles the cautious members.' },
      { t:'Withdraw and ask to revisit next quarter.',                                               quota:-10, morale:+4,  risk:-4,  why:'Avoids friction but surrenders all momentum.' },
    ]},
]

export const RANKS: Rank[] = [
  { name:'Rookie',       minXp:0 },
  { name:'Field Rep',    minXp:200 },
  { name:'Style Reader', minXp:500 },
  { name:'Drive Expert', minXp:1000 },
  { name:'Style Master', minXp:2000 },
]

export const XP_VALUES: XpValues = {
  correct:       20,
  fastBonus:     10,
  levelComplete: 50,
  perfectLevel:  100,
  dailyStreak:   30,
}

export const LEVELS = [
  { n:1, title:'Style Scan',    sub:'Read behaviour, name the style' },
  { n:2, title:'Crisis Mode',   sub:'Defuse the objection under fire' },
  { n:3, title:'Drive Decoder', sub:'Satisfy the underlying drive' },
  { n:4, title:'The Formulary', sub:'Balance Adoption, Trust & Risk' },
]
